"""Add pending_investments table

Revision ID: 45f09f84b4e3
Revises: ad61fc4aeed6
Create Date: 2025-12-04 11:55:30.921086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f09f84b4e3'
down_revision: Union[str, Sequence[str], None] = 'ad61fc4aeed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('detailed_notes', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False, server_default='THB'),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('committed_amount', sa.Numeric(precision=14, scale=2), nullable=True, server_default='0.0'),
    sa.Column('funding_source', sa.String(), nullable=True),
    sa.Column('target_start_date', sa.Date(), nullable=True),
    sa.Column('expected_completion_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False, server_default='Medium', comment='Critical / High / Medium / Low'),
    sa.Column('status', sa.String(), nullable=False, server_default='Planned', comment='Planned / Approved / In Progress / Completed / Cancelled'),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_investments_id'), 'pending_investments', ['id'], unique=False)
    op.create_index('ix_pending_investments_location', 'pending_investments', ['location'], unique=False)
    op.create_index('ix_pending_investments_priority', 'pending_investments', ['priority'], unique=False)
    op.create_index(op.f('ix_pending_investments_ref_code'), 'pending_investments', ['ref_code'], unique=True)
    op.create_index('ix_pending_investments_status', 'pending_investments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pending_investments_status', table_name='pending_investments')
    op.drop_index(op.f('ix_pending_investments_ref_code'), table_name='pending_investments')
    op.drop_index('ix_pending_investments_priority', table_name='pending_investments')
    op.drop_index('ix_pending_investments_location', table_name='pending_investments')
    op.drop_index(op.f('ix_pending_investments_id'), table_name='pending_investments')
    op.drop_table('pending_investments')
    # ### end Alembic commands ###
