"""Add income table

Revision ID: a36cf14820fd
Revises: 
Create Date: 2025-12-04 11:20:27.773715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36cf14820fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PAID', 'PENDING', 'OVERDUE', 'CANCELLED', name='incomestatus'), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_doc_date'), 'income', ['doc_date'], unique=False)
    op.create_index('ix_income_doc_date_location', 'income', ['doc_date', 'location'], unique=False)
    op.create_index(op.f('ix_income_doc_no'), 'income', ['doc_no'], unique=True)
    op.create_index(op.f('ix_income_id'), 'income', ['id'], unique=False)
    op.create_index('ix_income_status', 'income', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_income_status', table_name='income')
    op.drop_index(op.f('ix_income_id'), table_name='income')
    op.drop_index(op.f('ix_income_doc_no'), table_name='income')
    op.drop_index('ix_income_doc_date_location', table_name='income')
    op.drop_index(op.f('ix_income_doc_date'), table_name='income')
    op.drop_table('income')
    # ### end Alembic commands ###
