"""Add recurrency and forecasting columns to expenses

Revision ID: ad61fc4aeed6
Revises: 5ebd51d23a5a
Create Date: 2025-12-04 11:54:09.504104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad61fc4aeed6'
down_revision: Union[str, Sequence[str], None] = '5ebd51d23a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('is_recurring', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('expenses', sa.Column('recurrence_period', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('forecasted_until', sa.Date(), nullable=True))
    op.create_index(op.f('ix_expenses_is_recurring'), 'expenses', ['is_recurring'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_is_recurring'), table_name='expenses')
    op.drop_column('expenses', 'forecasted_until')
    op.drop_column('expenses', 'recurrence_period')
    op.drop_column('expenses', 'is_recurring')
    # ### end Alembic commands ###
